name: Build .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install zip
      run: sudo apt-get update && sudo apt-get install -y zip

    - name: Publish Single File Executable for Linux
      run: |
        dotnet publish -c Release -r win-x64 --self-contained true \
        /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:ReadyToRun=true

    - name: Remove Windows artifacts
      run: |
        if [ -d "./bin/Release/net9.0/win-x64" ]; then
          rm -rf ./bin/Release/net9.0/win-x64
        fi

    - name: Create ZIP Archive
      run: zip -r PublishedExecutable-linux-x64.zip ./bin/Release/net9.0

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ github.run_number }}"
        release_name: "Release v${{ github.run_number }}"
        body: "This release includes the latest build of the .NET application for Linux."
        draft: false
        prerelease: false
    
    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./PublishedExecutable-linux-x64.zip
        asset_name: PublishedExecutable-linux-x64.zip
        asset_content_type: application/zip
